import { type ProjectCard, PLATFORM_META } from './types';

// Replace with API call: GET /api/projects
export const projects: ProjectCard[] = [
  {
    id: '1',
    title: 'Podcast Ep. 47 — Build in Public',
    description: 'Breaking down the realities of building a SaaS solo, from zero to first $10k MRR.',
    status: 'Active',
    source: 'YouTube',
    duration: '24:38',
    platforms: [PLATFORM_META.instagram, PLATFORM_META.linkedin, PLATFORM_META.twitter],
    thumbnailGradient: 'from-[#1a0a2e] via-[#16213e] to-[#0f3460]',
    thumbnailAccent: 'rgba(167,139,250,0.35)',
    stats: { views: '48.2K', engagement: '6.4%', posts: 28 },
    outputs: { done: 28, total: 30 },
    updatedAt: '2 minutes ago',
    tags: ['SaaS', 'Indie Hacking'],
  },
  {
    id: '2',
    title: 'YouTube Deep Dive — AI Tools 2025',
    description: 'Comprehensive breakdown of the top AI productivity tools reshaping content creation.',
    status: 'Active',
    source: 'YouTube',
    duration: '18:22',
    platforms: [PLATFORM_META.youtube, PLATFORM_META.twitter, PLATFORM_META.facebook],
    thumbnailGradient: 'from-[#0a1628] via-[#0d2137] to-[#0a0a0a]',
    thumbnailAccent: 'rgba(255,85,85,0.3)',
    stats: { views: '124K', engagement: '8.1%', posts: 30 },
    outputs: { done: 30, total: 30 },
    updatedAt: '1 hour ago',
    tags: ['AI Tools', 'Productivity'],
  },
  {
    id: '3',
    title: 'Solo Creator Masterclass — Week 12',
    description: 'Week 12 of the ongoing masterclass series covering advanced monetization strategies.',
    status: 'Scheduled',
    source: 'Loom',
    duration: '31:05',
    platforms: [PLATFORM_META.instagram, PLATFORM_META.pinterest],
    thumbnailGradient: 'from-[#0a1a0a] via-[#112211] to-[#0a0f0a]',
    thumbnailAccent: 'rgba(52,211,153,0.3)',
    stats: { views: '19.7K', engagement: '5.2%', posts: 30 },
    outputs: { done: 30, total: 30 },
    updatedAt: '3 hours ago',
    tags: ['Masterclass', 'Monetization'],
  },
  {
    id: '4',
    title: 'Q2 Content Strategy — Agency Brief',
    description: 'Full Q2 strategic content brief for the agency account — multi-platform rollout.',
    status: 'Processing',
    source: 'Upload',
    duration: '45:17',
    platforms: [PLATFORM_META.linkedin, PLATFORM_META.twitter, PLATFORM_META.facebook],
    thumbnailGradient: 'from-[#0a0e1a] via-[#0d1528] to-[#080808]',
    thumbnailAccent: 'rgba(96,165,250,0.3)',
    stats: { views: '—', engagement: '—', posts: 0 },
    outputs: { done: 0, total: 30 },
    updatedAt: '12 minutes ago',
    tags: ['Agency', 'Strategy'],
  },
  {
    id: '5',
    title: 'Newsletter Series — Founder Stories',
    description: 'Long-form interview series featuring early-stage founders and their origin stories.',
    status: 'Archived',
    source: 'Podcast',
    duration: '52:40',
    platforms: [PLATFORM_META.facebook, PLATFORM_META.linkedin],
    thumbnailGradient: 'from-[#0f0f0f] via-[#141414] to-[#0a0a0a]',
    thumbnailAccent: 'rgba(255,255,255,0.1)',
    stats: { views: '31.4K', engagement: '4.8%', posts: 30 },
    outputs: { done: 30, total: 30 },
    updatedAt: 'Yesterday',
    tags: ['Newsletter', 'Interviews'],
  },
  {
    id: '6',
    title: 'Product Demo — CreatorOS v2 Launch',
    description: 'Full product walkthrough video for the v2 launch event — repurposed for all platforms.',
    status: 'Active',
    source: 'Loom',
    duration: '14:52',
    platforms: [PLATFORM_META.youtube, PLATFORM_META.instagram, PLATFORM_META.linkedin, PLATFORM_META.twitter],
    thumbnailGradient: 'from-[#1a0f00] via-[#201500] to-[#0a0a0a]',
    thumbnailAccent: 'rgba(251,146,60,0.3)',
    stats: { views: '87.3K', engagement: '9.2%', posts: 30 },
    outputs: { done: 30, total: 30 },
    updatedAt: '2 days ago',
    tags: ['Product', 'Launch'],
  },
  {
    id: '7',
    title: 'Creator Economy Report — May 2025',
    description: 'Data-driven analysis of creator economy trends distilled into multi-platform content.',
    status: 'Draft',
    source: 'Upload',
    duration: '28:15',
    platforms: [PLATFORM_META.linkedin, PLATFORM_META.pinterest],
    thumbnailGradient: 'from-[#0a0a1a] via-[#0d0d20] to-[#080808]',
    thumbnailAccent: 'rgba(167,139,250,0.2)',
    stats: { views: '—', engagement: '—', posts: 0 },
    outputs: { done: 0, total: 30 },
    updatedAt: '4 days ago',
    tags: ['Report', 'Creator Economy'],
  },
  {
    id: '8',
    title: 'Behind the Build — Startup Diary',
    description: 'Raw, unfiltered startup diary episode covering a pivotal product decision week.',
    status: 'Active',
    source: 'YouTube',
    duration: '22:10',
    platforms: [PLATFORM_META.youtube, PLATFORM_META.instagram, PLATFORM_META.twitter],
    thumbnailGradient: 'from-[#150a0a] via-[#1f1010] to-[#0a0808]',
    thumbnailAccent: 'rgba(248,113,113,0.3)',
    stats: { views: '56.8K', engagement: '7.3%', posts: 30 },
    outputs: { done: 30, total: 30 },
    updatedAt: '5 days ago',
    tags: ['Startup', 'Vlog'],
  },
];
